[build]
  publish = "dist/prod"
  command = "npm run pack"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"